name: Push stable
on:
  push:
    paths:
      - .github/workflows/push-stable.yaml
  pull_request:
    paths:
      - .github/workflows/push-stable.yaml
  workflow_dispatch:
    inputs:
      push:
        type: boolean
        default: false
        description: Should the image be pushed

env:
  IMAGE: ghcr.io/${{ vars.IMAGE_PROJECT || 'vshn' }}/kaniko
  PUSH: ${{ inputs.push || startsWith(github.ref, 'refs/heads/main') }}

jobs:
  # the latest of the flavor debug is called debug
  retag-nightly-to-latest:
    runs-on: ubuntu-24.04
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: retag image
        run: |
          # renovate: datasource=docker depName=ghcr.io/vshn/kaniko
          TAG="nightly-debug@sha256:28c014b4fb753a77ca8bc38b8ec87e2ceb9b696c720c1babc466e3c827596ea8"

          docker pull ghcr.io/vshn/kaniko:$TAG
          docker tag ghcr.io/vshn/kaniko:$TAG ${{ env.IMAGE }}:debug
          if [ "${{ env.PUSH }}" = "true" ]; then
            docker push ${{ env.IMAGE }}:debug
          fi
